language: node_js
node_js:
  - '8'
branches:
  only:
    - master
sudo: required
before_install:
  - npm i yarn@latest -g
cache:
  yarn: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - yarn format:ci
  - yarn build
  - yarn check:all
  - yarn test
env:
  global:
    secure: IaLnA8heZU8OMLiA8REbZeF1F5uXJE5XmX7L0cmtNYtHNDs+p4ufVOOGbrfZW2fDEbDpXryT3lTNsFLPPmHT0sdwH/eNeO+VNvqcJW4kHe6UReVU6fObsdEvGbX4V8V08x7V4rbJjHgERq9e8O0DDp32ykxuu1XbUlb01NEu1Qg=
